(autoload 'yas/jit-cache                        "yas-jit" "" nil)
(autoload 'yas/jit-delete-cache                 "yas-jit" "" t)
(autoload 'yas/get-jit-loads                    "yas-jit" "" nil)
(autoload 'yas/jit-hook                         "yas-jit" "" t)
(autoload 'yas/jit-hook-run                     "yas-jit" "" nil)
(autoload 'yas/load-snippet-dirs                "yas-jit" "" nil)
(autoload 'yas/jit-dir-snippet-cache            "yas-jit" "" nil)
(autoload 'yas/jit-compile-bundle               "yas-jit" "" t)
(autoload 'yas/jit-compile-dir                  "yas-jit" "" t)
(provide 'yas-git-epkg-autoloads)
